### ISSUE TITLE
File name for DB downloaded dataset is being appended with random string

### ISSUE THREAD

**Issue by MattPerrine** [cfpb/hmda-frontend#430] opened 2020-05-11 12:59 UTC
When the filter is set to 'Dwelling Categories' the file name is being appended with 
a string of random letters and numbers. For example:

State: GA
FI: Ameris Bank
Filter: Dwelling Categories - Single Family (1-4 Units):Site-Built

year_2018_msamd_12060_lei_IUGPUX5LWRZ3B6KIZ697_dwelling_categories_Single Family (1-4 Units)_Site-Bu49cfd87b2efd878e856313d8b49ca758.csv

In contrast, when the filter is set to 'Action Taken' the file name appears correct:

State: GA
FI: Ameris Bank
Filter: Action Taken - 1 

File name: year_2018_state_GA_lei_IUGPUX5LWRZ3B6KIZ697_actions_taken_1.csv **(this is correct)**

**Comment by meissadia** [comment] 2020-05-13 17:46
Hey @MattPerrine , just wanted to verify the expected format on the filename issue https://github.com/cfpb/hmda-frontend/issues/430
 
It looks like categories (year, geography, variables, institutions) are underscore separated.   Checking in Prod, it looks like items within a category (multiple leis/states/etc) are hyphen separated?
 
So, expanding on the provided `correct` example with multiple states and multiple filter options selected:
```
State: GA, MI
FI: Ameris Bank
Filter: Action Taken - 1,2
```
filename would be => `year_2018_states_GA-MI_leis_IUGPUX5LWRZ3B6KIZ697_actions_taken-1-2.csv`

Also, the filter options include some characters which are restricted for filenames (colons `:` and forward-slashes `/` that I've seen so far ex. Loan Product => FSA/RHS:First Lien).  Is it ok to replace these with a blank space or do we want some other kind of character substitution there?

**Comment by omnipresent07** [comment] 2020-05-15 15:21
@MattPerrine I just tried this out and the file that got downloaded is: `year_2018_state_GA_lei_IUGPUX5LWRZ3B6KIZ697_dwelling_categories_Single Family (1-4 Units)_Site-Built.csv` --> without the gibberish in the end. Can you please see if this is reproducible on your end?

**Comment by MattPerrine** [comment] 2020-05-15 15:46
@meissadia @omnipresent07 - I just downloaded a file from DB and the order of the variables in the file name is different. The file name order I'm seeing is:
dwelling_categories_Single Family (1-4 Units)_Site-Built_year_2018_lei_IUGPUX5LWRZ3B6KIZ697_state_GA

**Comment by meissadia** [comment] 2020-05-15 18:35
Filename
- lower case everything
- singular category (lei instead of leis)
- replace parentheses, colons, forward slashes (replace with underscore)
- separate items with underscore
- separate categories with -

**Comment by omnipresent07** [comment] 2020-05-21 12:26
https://github.com/cfpb/hmda-platform/issues/3680

**Comment by meissadia** [comment] 2020-05-22 20:49
Tested again in Prod with GA/Ameris/Dwelling but it looks like the file was already cached since it came from S3. 

Filename was `dwelling_categories_Single Family (1-4 Units)_Site-Built_year_2018_lei_IUGPUX5LWRZ3B6KIZ697_state_GA.csv`

Tested GA/Ameris/Action Taken, also cached, filename was `actions_taken_1_year_2018_lei_IUGPUX5LWRZ3B6KIZ697_state_GA.csv`

Found GA/Suncoast Credit Union/Action Taken which was not cached and the filename matched the cached format: `actions_taken_1_year_2018_lei_549300TOOOOW36EX6R40_state_GA.csv`

This looks good to me 👍.  Closing.

**Closed by meissadia** 2020-05-22 20:49 UTC
Labels: bug, data-browser
