### ISSUE TITLE
Printing Receipt on Filing Summary Page

### ISSUE THREAD

**Issue by audayshankar** [cfpb/hmda-frontend#923] opened 2021-04-20 15:07 UTC
When printing the Filing Summary receipt, the print view removes the checkboxes.

![image](https://user-images.githubusercontent.com/58990254/115419536-68e06680-a1c8-11eb-9cbe-5ded916272da.png)

**Comment by meissadia** [comment] 2021-05-20 15:57
Hello @audayshankar,

Can you please verify that this is still an issue?  I'm unable to recreate this on either Windows or OSX.  I believe it was originally spotted on Win/Chrome.  IE does not offer a print preview.

### Windows - Chrome
<img width="1081" alt="Win-Chromes" src="https://user-images.githubusercontent.com/2592907/119010562-6dc44180-b951-11eb-9f40-7a71f76bd600.png">

### OSX - Safari
<img width="772" alt="OSX-Safaris" src="https://user-images.githubusercontent.com/2592907/119010515-5dac6200-b951-11eb-8af2-797a8e534bc0.png">


### OSX - Chrome
<img width="1084" alt="OSX-Chrome-s" src="https://user-images.githubusercontent.com/2592907/119010446-4a999200-b951-11eb-97a9-49fe382b77e7.png">

**Comment by meissadia** [comment] 2021-05-27 17:42
Did a screen share with audayshankar but was unable to pinpoint the issue.
 
Via print view emulation, we verified that the check marks are visible in the print layout.  However, once the page is reprocessed in the Print dialog, the check marks disappear.  The check marks are also absent from the generated PDF.

**Comment by meissadia** [comment] 2021-07-12 15:39
- Tried Chrome on my personal machine and was able to see the checkmarks.  
- Tested again on Windows Chrome, still shows as expected for me.

**Comment by meissadia** [comment] 2021-07-16 17:12
Closing as this was an internally identified issues, I'm unable to reproduce, and multiple pairing sessions did not help identify the issue.  We can re-open if we find this affecting users.

**Closed by meissadia** 2021-07-16 17:12 UTC
Labels: bug
