### ISSUE TITLE
Data Publication: Aggregate Report Freezing Page

### ISSUE THREAD

**Issue by sthomas93** [cfpb/hmda-frontend#1561] opened 2022-09-22 17:13 UTC
When selecting N/A or outside MSA/MD - NA the browser freezes potentially due to the large file processing. 

![image](https://user-images.githubusercontent.com/99903050/191808690-51d89674-fb1b-47cb-b10f-ce817f161eaa.png)

![image](https://user-images.githubusercontent.com/99903050/191809790-2768c427-d4af-48a7-993d-630b71b7e611.png)

https://ffiec.cfpb.gov/data-publication/aggregate-reports/2021

**Comment by meissadia** [comment] 2022-09-22 21:41
## Initial Findings
I've been trying to find a version of the Frontend code for which this report would successfully load. I've gone all the way back to Frontend v1.0.0 (December 2019) and the issue occurs even for the 2018 version of this report (NA/99999/1). So this does not seem to be something newly broken or caused by recent Frontend dependency updates as initially suspected.
 
In my spot testing, the upper limit for the number of Tracts we can display before the browser freezes is around 2,500 (3,000 results in crash). The 2018 (NA/99999/1) report has over 12,000, 2021 has almost 11,900.  For reference, looking at some larger MSA/MDs such as [LOS ANGELES (CA/31084/1)](https://ffiec.cfpb.gov/data-publication/aggregate-reports/2018/CA/31084/1
) I see 2,322 entries in 2021 and the report renders without issue (the number of included Tracts is not displayed on the webpage, this count was determined via code).
 
I think we need to virtualize the display of these components, so that only the elements/Tracts that are currently visible in the browser window are actually rendered in the React DOM. The goal here is to greatly reduce the memory allocation and hopefully enable these gigantic reports to display. 

https://blog.logrocket.com/rendering-large-lists-with-react-virtualized-82741907a6b3/
 
## Downsides
One downside is that I think this would prevent users from being able to do a text search on the page if they were looking for a particular tract. Using the above referenced LOS ANGELES report as an example, if a user were looking for Tract `620101` they could `CTRL/CMD + F` and search to quickly be taken to the table of interest. 
 
In an ocean of 12000 (or even 2500) tables this would seem to be a crucial capability. So we may need to build some filtering functionality to make the Virtualized approach more usable.  
 
If we need more time to design and implement the filtering functionality, as an intermediate step we could do a check for how many Tracts are included in the report and only virtualize if over the 2,500 mark. This would preserve the simple text search capability for "smaller" reports. 
 
Alternately, since users can also download the CSV, they could do the search/filtering in their own application of choice. 
 
## Upsides
At the very least, virtualization would at least allow the report to render and allow users access to the `Save as CSV` button so that further inspection of the data was possible.

**Comment by meissadia** [comment] 2022-09-23 00:04
This affects both `1 - Applications by Tract` and `2 - Loans Purchased by Tract`

**Comment by meissadia** [comment] 2022-09-23 00:07
https://github.com/bvaughn/react-window is already used elsewhere in our project, so we will explore it's use as opposed to `react-virtualized`.
 
 Another great option Michael proposed is pagination: https://www.npmjs.com/package/react-paginate

**Comment by meissadia** [comment] 2022-09-23 18:25
## Approach 1 - Virtualization - `react-window`
Initial attempts to implement virtualization of the data table using `react-window` have been unsuccessful.  Due to the way that the library implements its windowed container, the virtualized portion of the table winds up compressed and restricted to the first column.

In terms of performance, virtualization does resolve the browser crashing while allowing full (scrolling) access to the data. 
 
I have also confirmed my initial concern that users would no longer be able to search all of the tabular data via the browser's `CMD+F` function. 

`react-virtualized` actually has a [Table](https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md) component so I will be trying that next.

## Screenshots
<img width="1168" alt="react-window-in-table" src="https://user-images.githubusercontent.com/2592907/192031078-d0d88ce3-84a8-4611-83d0-3a7aac6f305c.png">

**Comment by Michaeldremy** [comment] 2022-09-23 19:58
# Approach 2 - Adding pagination

Implemented pagination by using [react-paginate](https://www.npmjs.com/package/react-paginate). Pages are generated based off of tracts divided by 1000. Pagination tool does not display unless tracts is greater than 1000. 

## Testing

1. The report for [LOS ANGELES (CA/31084/1)](https://ffiec.cfpb.gov/data-publication/aggregate-reports/2018/CA/31084/1) in Meissa initial findings loads faster and generates 3 pages. 

2. The report `N/A or outside MSA/MD - NA` no longer crashes and it generates 12 pages.

## Closing thoughts

The report for `N/A or outside MSA/MD - NA` no longer crashes the browser but we might want to increase pages generated to further help performance. 

# Screenshots

[LOS ANGELES (CA/31084/1)](https://ffiec.cfpb.gov/data-publication/aggregate-reports/2018/CA/31084/1) report
<img width="996" alt="image" src="https://user-images.githubusercontent.com/60801873/192047358-3eaffc52-e0d2-4b13-8cad-49ad0a607088.png">

`N/A or outside MSA/MD - NA` report
<img width="994" alt="image" src="https://user-images.githubusercontent.com/60801873/192047193-e888f1a6-5de2-45d7-8f4a-9aa9a251b8f1.png">

**Closed** 2022-10-04 20:09 UTC
Labels: bug, data-publication
